export const movies = [
  {
    title: "The Shawshank Redemption",
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: 1990,
    overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    vote_average: 9.3,
    genres: "Drama",
    id: 1230,
  },
  {
    title: "The Godfather",
    poster_path: "/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg",
    release_date: 1972,
    overview: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    vote_average: 9.2,
    genres: "Crime-Drama",
    id: 1239,
  },
  {
    title: "The Dark Knight",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: 2008,
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    vote_average: 9.0,
    genres: "Action-Crime-Drama",
    id: 1248,
  },
  {
    title: "Forrest Gump",
    poster_path: "/h5J4W4veyxMXDMjeNxZI46TsHOb.jpg",
    release_date: 1994,
    overview: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    vote_average: 8.8,
    genres: "Comedy-Drama-Romance",
    id: 1257,
  },
  {
    title: "Inception",
    poster_path: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    release_date: 2010,
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    vote_average: 8.7,
    genres: "Action-Adventure-Sci-Fi",
    id: 1266,
  },
  {
    title: "The Matrix",
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    release_date: 2021,
    overview: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    vote_average: 8.6,
    genres: "Action-Sci-Fi",
    id: 1275,
  },
  {
    title: "Pulp Fiction",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 1995,
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 1284,
  },
  {
    title: "Avengers",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 2013,
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 23545,
  },
  {
    title: "The queen",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 1989,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 758,
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: 2003,
    overview: "Aragorn is revealed as the heir to the ancient kings as he-Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile-Frodo and Sam bring the ring closer to the heart of Mordor-the dark lord's realm.",
    vote_average: 8.5,
    genres: "Adventure-Fantasy-Action",
    id: 122,
  },
  {
    title: "Love",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 2020,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Adventure",
    id: 7645,
  },
  {
    title: "Sex and the city",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 2023,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 987553,
  },
  {
    title: "Scream",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 2004,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 75643,
  },
  {
    title: "Blue",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 1998,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 1284645,
  },
  {
    title: "Horrible bosses",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 2012,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 8757,
  },
  {
    title: "Avatar way of water",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 2022,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 1285454,
  },
  {
    title: "Idiots",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 1999,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 2142684,
  },
  {
    title: "Small town",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 2011,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 94362,
  },
  {
    title: "Clean slate",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: 2019,
    overview: "The lives of two mob hitmen-a boxer-a gangster and his wife-and a pair of diner bandits intertwine in four tales of violence and redemption.",
    vote_average: 8.5,
    genres: "Crime-Drama",
    id: 7362,
  },
  // add more movies here
];
